use_frameworks!

target 'SimpleNetworking_Example' do
  pod 'SimpleNetworking', :path => '../'

  target 'SimpleNetworking_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
