use_frameworks!

target 'TermiNetwork_Example' do
  pod 'TermiNetwork', :path => '../'

  target 'TermiNetwork_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
